### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by gsimone** [accurat/yogurt-layout#1]
Hey! 👋 Great little lib, I'm playing around with it and react-three-fiber, since laying stuff out is usually painful: https://codesandbox.io/s/blissful-lake-84hxp (<= this might explode while I work on it :D )

Here's a couple of quick things:

1. `gap` and `margin` properties. In the example I wanted to add some gap between items, it would be great being able to do it without having to add a container
2. `direction` could default to `row` like `flex-direction` does in css
3. `height` and `width` defaults (`auto` probably), just to reduce boilerplate

Anyway, main message is: Kudos, this is great!

**Comment by caesarsol** [comment]
Hi Gianmarco, thanks for this very early feedback! Cool little example :)

You make good points:
1. `gap` and `margin` is exactly the direction we had the intention to go
2. and 3. I did make a choice to avoid defaults in this early stage, but your comment makes me realize it's a pretty strange choice :D `row` and `auto` is definitely the way to go.

We are also adding a little feature to set the dimension of a Block based on its children's dimensions, do you think that could be useful?

**Comment by gsimone** [comment]
Something like this, right?

```
makeLayout({
  id: "root",
  children: [{
       id: "1",
       width: 200
    },
    {
      id: "2",
      width: 300
    }]
})

// layout.root.width = 500
```

**Comment by caesarsol** [comment]
Yes, we'd make the choice explicit by setting something like `width: 'children'`, and then we'll need to error out if a children has a percentage or `auto`.
